### ISSUE TITLE
Does not currently build and run at HEAD

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-react-frontend-playground#1]

**Comment by garvankeeley** [comment]
I'll pull a clean repo and see what is going on

**Comment by devinreams** [comment]
>I'll pull a clean repo and see what is going on

@garvankeeley Cool. No biggie, but I appreciate you looking at it.

If it's more than a "small" effort, feel free to pass on this.

**Comment by garvankeeley** [comment]
Fixed by 2ff6b1e82ef940371c26e0adac101a45228eaaa5

**Comment by devinreams** [comment]
Aha! It's working for me now. Thanks @garvankeeley!
